### ISSUE TITLE
The thinglab link doesn't currently work

### ISSUE THREAD

**Issue by GregDavidson** [cdglabs/thinglab#2]
Clicking on www.cdglabs.org/thinglab/ takes me to http://iyfbodn.com/?dn=cdglabs.org&pid=9POT3387I&pbsubid=729110dc-0f49-3089-3ff1-5e8550c54ae3&noads=http%3A%2F%2Fiyfbodn.com%2F%3Fdn%3Dcdglabs.org%26skipskenzo%3Dtrue

I hope it's back up soon as I like to show it to people.

Do you know if anyone's porting ThingLab to a modern Smalltalk or other modern platform?  I'd love to participate with such a project!

**Comment by codefrau** [comment]
Thank you for noticing!

It looks like the cdglabs.org domain expired. I will try to move it to a regular GitHub page.

In the mean time, you can download the [zip](https://github.com/cdglabs/thinglab/archive/refs/heads/gh-pages.zip) and point a local web server to that directory. I just tried that, works fine.

**Comment by alanb2718** [comment]
Also I have a copy of ThingLab available on a machine at UW:
https://constraints.cs.washington.edu/thinglab/

  cheers,
  Alan

**Comment by codefrau** [comment]
I fixed it. Now lives on GitHub Pages here:

https://cdglabs.github.io/thinglab/

**Comment by GregDavidson** [comment]
Thank you for the amazing response!

Do you know if anyone is currently engaged in porting ThingLab to a modern
platform?

If there were such a project and it were FLOSS I would love to help!

_Greg

**Comment by alanb2718** [comment]
I don't know of anyone working on this, but if I hear of someone I'll let you know!  Could be a fun project.  (I haven't been working on this myself for some years - the last project I was working on related to ThingLab and successors was a new constraint-based reactive programming language, but that is currently dormant.)

**Comment by GregDavidson** [comment]
Thank you Alan!  I'm a longtime fan.  ThingLab was revolutionary in its day
and ThingLab would be revolutionary today!

_Greg
